### ISSUE TITLE
Incorrect grammar: Cannot find file within this repo

### ISSUE THREAD

**Issue by cheeeeeeeeeen** [sleeper-service-CE/FTL-Captain-s-Edition-Spell-Checking-2016#19]
![image](https://cloud.githubusercontent.com/assets/26833961/24585056/c17a7c7a-17b3-11e7-9af4-13d141383393.png)

> "According to the Intel, this _**sectors**_ governments [...]"

I found a wrong grammar, but I cannot find this paragraph from anywhere of the files.
Is this by chance a vanilla FTL event? If so, then please close this issue.

**Comment by blizzarchon** [comment]
This is mostly likely text added from **CE Infinite**, as seen by the 5 jumps fleet delay. There may be other errors, as I do recall seeing either this or something else...

**Comment by sleeper-service-CE** [comment]
Fixed in infinite files, thanks for letting me know.
