### ISSUE TITLE
Tense Problem in Hazard Nano-bot Background Image

### ISSUE THREAD

**Issue by cheeeeeeeeeen** [sleeper-service-CE/FTL-Captain-s-Edition-Spell-Checking-2016#21]
![image](https://cloud.githubusercontent.com/assets/26833961/24646099/4c9dfef4-194d-11e7-8749-e9931a4115da.png)

`The fleet can't track you here, but all systems will be jammed and your ship will take some damage.`

OR

`The fleet can't track you here, but all systems are jammed and your ship takes some damage.` (I prefer this one)

**Comment by sleeper-service-CE** [comment]
Thanks for pointing it out. Fixed in the images now using your second suggestions.
