### ISSUE TITLE
Ambiguous error?

### ISSUE THREAD

**Issue by cheeeeeeeeeen** [sleeper-service-CE/FTL-Captain-s-Edition-Spell-Checking-2016#23]
![image](https://cloud.githubusercontent.com/assets/26833961/25079019/35adf0dc-236b-11e7-99a6-f09dbd67f1dc.png)

This line can be found in:
`Line 6381`
`Line 6458`
in events_pirate.xml.append

> [...]but I they might try to[...]

I don't know what's the meaning of the sentence. What is the pirate lord trying to say here? I can't seem to figure it out. I will also rephrase the paragraph after this has become clear.

**Comment by blizzarchon** [comment]
I don't know what the pirate lord's saying but I bet placing "thought" in between "I" and they" will solve the problem. I'd have to look at the event in more detail to figure out what they're trying to see, and I don't have the energy for that right now.
