### ISSUE TITLE
broken Fed. Store text (in STORE_FED_TEXT in events_boss.xml.append)

### ISSUE THREAD

**Issue by blizzarchon** [sleeper-service-CE/FTL-Captain-s-Edition-Spell-Checking-2016#27]
It reads as follows:
`<text planet="PLANET_POPULATED_REAL">A trade hub orbits this Federation controlled planet. You check their offers and</text>`
As you can see, the sentence is cut off. Any idea where the rest of the sentence is or what it should be?

**Comment by sleeper-service-CE** [comment]
Hm weird, which event is that used in?

      Von: BlizzArchonJ <notifications@github.com>
 An: sleeper-service-CE/FTL-Captain-s-Edition-Spell-Checking-2016 <FTL-Captain-s-Edition-Spell-Checking-2016@noreply.github.com> 
CC: Subscribed <subscribed@noreply.github.com>
 Gesendet: 18:47 Freitag, 16.Juni 2017
 Betreff: [sleeper-service-CE/FTL-Captain-s-Edition-Spell-Checking-2016] broken Fed. Store text (in STORE_FED_TEXT in events_boss.xml.append) (#27)
   
It reads as follows:
<text planet="PLANET_POPULATED_REAL">A trade hub orbits this Federation controlled planet. You check their offers and</text>
As you can see, the sentence is cut off. Any idea where the rest of the sentence is or what it should be?—

**Comment by blizzarchon** [comment]
it's the starting Store text for Federation Controlled Sectors (so also including The Last Stand), so the event "STORE_FED"

**Comment by sleeper-service-CE** [comment]
"A trade hub orbits this Federation controlled planet. You check their offers and consider whether to profit from their "Galactic Armageddon" sales." Don't remember the original, feel free to make up something else that fits the situation.

**Comment by blizzarchon** [comment]
I'll just go with that, if I think of something better I guess I'll change it? anyways I made a pull request regarding this.
