### ISSUE TITLE
Incorrect spelling of 'maneuver' during confined space special event

### ISSUE THREAD

**Issue by countjocular** [sleeper-service-CE/FTL-Captain-s-Edition-Spell-Checking-2016#9]
The explanatory text for the CE_CONSTRUCTION_SPACE_FACTORY_ITEMS special event reads

> `You're in confined space. With no space to meneuver, ships present ...`

This should of course read

> `You're in confined space. With no space to maneuver, ships present ...`

![212680_20170115010559_1](https://cloud.githubusercontent.com/assets/2001/22330799/e10e3090-e3bf-11e6-8cb1-52c96eaee881.png)

I would have submitted a pull request for this, but I couldn't find the string within the repository files, so I can only assume it's compiled from elsewhere.

**Comment by blizzarchon** [comment]
_"I couldn't find the string within the repository files,"_
you can open the data.dat file itself, search for the string (it must be there) then navigate upwards until you find which file it's in.

**Comment by sleeper-service-CE** [comment]
I think countjocular is talking about the fixed tooltip above the environmental danger indicator, which indeed has no string anywhere and is actually part of the background image. Thanks for pointing it out, I'll fix that manually.

**Comment by blizzarchon** [comment]
oh, sorry I just glanced over at it thinking it was the event. yeah that's pretty clear now that it would be the image. I didn't know that hazard even existed O.o

**Comment by sleeper-service-CE** [comment]
Appears on rare occasions in auto controlled sectors. ;)

**Comment by sleeper-service-CE** [comment]
Fixed in CE 1.299.
